baseURL = 'https://blog.moddinginquisition.org/'
languageCode = 'en-us'
title = 'ModdingInquisition Blog'
theme = "mainroad"

[Params]
  description = "ModdingInquisition Blog" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mainSections = ["personal", "announcements"]

[Params.style.vars]
highlightColor = "#e22d30" # Override highlight color

[Params.logo]
  image = "img/logo.png"
  title = "Blog"
  subtitle = "Regular updates about the Inquisition" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
